### ISSUE TITLE
blank/white screen with DISSIDIA FF NT (Free Edition)

### ISSUE THREAD

**Issue by ahjolinna** [kakra/wine-proton#12]
Square Enix just released [DISSIDIA FINAL FANTASY NT*](https://store.steampowered.com/app/921590/DISSIDIA_FINAL_FANTASY_NT_Free_Edition/) to PC/steam with also an free edition.

currently you will get blank/white screen with audio, apparently you can get into gameplay if know how to navigate the menu blindly

there is a "Proton/issues/2410"
and
here is mine log file: [steam-921590.log](https://github.com/kakra/wine-proton/files/2959068/steam-921590.log)

----
this was originally a arcade game (-series) made by TeamNinja that got ported to PS4 and now has free edition + PC port

**Comment by ahjolinna** [comment]
apparently this has been fixed in dxvk v1.0.2 / https://github.com/doitsujin/dxvk/pull/987

**Comment by kakra** [comment]
That version of DXVK will be in my next release. Currently I'm rebasing to Proton 4.2, I'll have to review over 450 commits in this process, so it will take some more time. But because a fix is available I'm closing this now.
