### ISSUE TITLE
Can't find where is the prepped package

### ISSUE THREAD

**Issue by mozo78** [kakra/wine-proton#3]
Hello,
I'm sorry for the dumb question but in the readme you mention just to extract dist.tar.xz. Where is this archive, it seems I can't find it nowhere. Thank you :)

**Comment by kakra** [comment]
Download it from here, it's named differenty, it's the `dist-...tar.xz`:
https://github.com/kakra/wine-proton/releases

**Comment by mozo78** [comment]
Thank you very much :)
