### ISSUE TITLE
Improve the Arch readme

### ISSUE THREAD

**Issue by mozo78** [kakra/wine-proton#5]
Hello,
you can improve the Arch readme a bit.

All packages from the first section can be installed with a single command:
`sudo pacman -Syu krb5 lib32-krb5 gst-plugins-base mpg123 openal sdl2 lib32-gst-plugins-base lib32-mpg123 lib32-openal lib32-sdl2 vulkan-icd-loader libxcomposite libxinerama lib32-vulkan-icd-loader lib32-libxcomposite lib32-libxinerama`

For the AUR packages use aurman for it will fetch the lib32-ffmpeg key automatically. And again with a single command:
`aurman -Syu ffmpeg spirv-tools lib32-ffmpeg lib32-spirv-tools`

**Comment by kakra** [comment]
I've split the lines to group them a little better. Sure, you can install it in one command but the lines become very long.

About `aurman`: I checked several options, and `aurman` is deprecated. Thus, I've chosen `pakku`. It also fetches the build files automatically, builds them, and then installs them.

I think that this should clear up all your suggestions?

**Comment by mozo78** [comment]
As you wish :)

**Comment by kakra** [comment]
I'm closing this because I suppose you know how to install pakku.

**Comment by copygirl** [comment]
The `meson` package also appears to be required separately.

**Comment by kakra** [comment]
Yes, it should probably explicitly listed... For some reason it was pulled automatically for me, probably by using `pakku`.

**Comment by kakra** [comment]
@copygirl Could you recheck with the current `README.md`? The instructions here are outdated, the issue has been closed. The current `README.md` says `pacman -Syu base-devel` which should've pulled in `meson`.

**Comment by copygirl** [comment]
The `base-devel` group itself [doesn't include](https://www.archlinux.org/groups/x86_64/base-devel/) it and I should already have all of them. (I was working from the current readme, by the way.)

**Comment by kakra** [comment]
Okay, then I'll add it. Thanks for reporting.
